name: flutter_base_architecture
description: A base framework to start with flutter
version: 1.0.1
author: Faiyyaz Shaikh
homepage: "https://github.com/faiyyazs/"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  fluttertoast: ^7.1.8
  shared_preferences: ^2.0.3
  connectivity: ^3.0.2
  dio: ^3.0.10
  flutter_svg: ^0.19.3
  rxdart: ^0.26.0
  dio_http_cache: ^0.2.11
 # steel_crypt: ^1.7.1+1

 # provider: ^5.0.0
#  fluttertoast: ^7.1.8
#  shared_preferences: ^2.0.3
#  connectivity: ^3.0.2
#  dio: ^3.0.0
#  cupertino_icons: ^1.0.0
#  flutter_svg: ^0.19.2
#  rxdart: ^0.24.0
#  dio_http_cache: ^0.2.11
#  steel_crypt: ^1.7.1+1
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

    # To add assets to your package, add an assets section, like this:
    #assets:
  #- asset/drawable/menu.png


  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
